apiVersion: v1
kind: Service
metadata:
  name: postgres-master-service
  namespace: postgres-ns
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      targetPort: 5432
