apiVersion: v1
kind: Service
metadata:
  name: postgres-slave-service
  namespace: postgres-ns
spec:
  type: NodePort
  selector:
    app: postgres
    role: slave
  ports:
    - name: postgres
      protocol: TCP
      port: 5435
      targetPort: 5432
