apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-slave
  namespace: postgres-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgres
      role: slave
  template:
    metadata:
      labels:
        app: postgres
        role: slave
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432

        env:
        - name: POSTGRES_PASSWORD
          value: randompassword
        volumeMounts:
        - name: postgres-slave-storage
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: init-scripts
        configMap:
          name: postgres-slave-config
  volumeClaimTemplates:
  - metadata:
      name: postgres-slave-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
