apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-slave-config
  namespace: postgres-ns
data:
  slave-config.sh: |
    # stop initial server to copy data
    pg_ctl -D /var/lib/postgresql/data/ -m fast -w stop
    rm -rf /var/lib/postgresql/data/*

    # add service name for DNS resolution
    PGPASSWORD=k8s-postgres-ha pg_basebackup -h postgres-master-service -w -U replicator -p 5432 -D /var/lib/postgresql/data -Fp -Xs -P -R

    # start server to keep container's screep happy
    pg_ctl -D /var/lib/postgresql/data/ -w start
    ;;
  create-replication-role.sql: |-
    CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'k8s-postgres-ha';