apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-master-config
  namespace: postgres-ns
data:
  master-config.sh: |
    echo "host    replication     all     all     md5" >> /var/lib/postgresql/data/pg_hba.conf
    echo "host    replication     all     all     trust" >> /var/lib/postgresql/data/pg_hba.conf
    echo "archive_mode = on"  >> /etc/postgresql/postgresql.conf
    echo "archive_command = '/bin/true'"  >> /etc/postgresql/postgresql.conf
    echo "archive_timeout = 0"  >> /etc/postgresql/postgresql.conf
    echo "max_wal_senders = 8"  >> /etc/postgresql/postgresql.conf
    echo "wal_keep_segments = 32"  >> /etc/postgresql/postgresql.conf
    echo "wal_level = hot_standby"  >> /etc/postgresql/postgresql.conf
    ;;
  create-replication-role.sql: |-
    CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'k8s-postgres-ha';
    SELECT pg_reload_conf();